### ISSUE TITLE
compare different data sets on the same taylor graph

### ISSUE THREAD

**Issue by iacopoff** [PeterRochford/SkillMetrics#10]
I was wondering if it was possible to plot multiple data sets (each one with several experiments) on one plot and then color the markers according to data set source? 

![image](https://user-images.githubusercontent.com/38247963/52400431-04d59a00-2ab7-11e9-9f45-d4ba269b388c.png)

**Comment by PeterRochford** [comment]
This is the first time I have received such a question or seen such a use of a Taylor diagram. It may be possible by making multiple calls to taylor_diagram, one for each data set and specifying a different color for the marker. I can experiment with the possibility if you email me some sample of the data you would like to plot: prochford@thesymplectic.com.

**Comment by iacopoff** [comment]
Hi Peter, an easy workaround I have tried is to append the Taylor statistics from one data set to the ones from the next data set and then define accordingly a list of labels as markerLabel in order to map to the Taylor statistic lists. However it is a bit messy with all the labels, and would be definitely better to use 
colours.
happy to send you some data. 
thanks

**Comment by PeterRochford** [comment]
The capability to create target and Taylor diagrams with multiple data sets overlaid has been added as of version 1.1.7. Refer to target diagram example 8 and Taylor diagram example 12 on the Wiki.
