### ISSUE TITLE
how can i convert pkl file to csv using python

### ISSUE THREAD

**Issue by smubeeeen** [PeterRochford/SkillMetrics#14]

**Comment by dayo-coder** [comment]
I am also very much interested in this, please. Anyone, please help. Thanks.

**Comment by PeterRochford** [comment]
There are many solutions for this on the Internet and your particular implementation will depend upon the contents of the pickle file. I've posted as a simple solution using pandas for the pkl file used for the example target scripts Q16 on the [FAQ](https://github.com/PeterRochford/SkillMetrics/wiki/FAQ).
