### ISSUE TITLE
how can i convert pkl file to csv using python

### ISSUE THREAD

**Issue by smubeeeen** [PeterRochford/SkillMetrics#15]
i have a pkl file and i need to see the datasets inside by changing the file to csv how can i do that?

**Comment by PeterRochford** [comment]
You can find out the contents of what has been loaded from a pkl file using the type() and vars() functions on the object loaded from the file. Some example code for the pkl file used for the example target scripts is posted as Q15 on the [FAQ](https://github.com/PeterRochford/SkillMetrics/wiki/FAQ). The key statements are copied below. 

    # Read data from pickle file
    with open('target_data.pkl3', 'rb') as f:
        object = pickle.load(f)
        
    # Report data type of object loaded from pickle file
    print('type(object): ', type(object))

    # Print the variables of the object loaded from pickle file
    pprint(vars(object))
