### ISSUE TITLE
As showed in taylor12_example.png ,the axis has a minus standard deviation

### ISSUE THREAD

**Issue by geoblog** [PeterRochford/SkillMetrics#17]
As showed in taylor12_example.png ,the axis has a minus standard deviation.Is it a bug?As I know in the Taylor_diagram_primer.pdf,the axis of standard deviation is non-negative. Is it right?

**Comment by PeterRochford** [comment]
Thank you for bringing this to my attention. You are correct that all the axis labels for standard deviation in a two-quadrant example should be positive. However, many scientists fail to do so out of expediency, to which I am also guilty. I've now fixed the bug.
