### ISSUE TITLE
Sample taylor1.py doesn't work

### ISSUE THREAD

**Issue by mobigroup** [PeterRochford/SkillMetrics#2]
```
python2 taylor1.py
Traceback (most recent call last):
  File "taylor1.py", line 101, in <module>
    sm.taylor_diagram(sdev,crmsd,ccoef)
  File "/usr/local/lib/python2.7/site-packages/skill_metrics/taylor_diagram.py", line 91, in taylor_diagram
    overlay_taylor_diagram_circles(axes,cax,option)
  File "/usr/local/lib/python2.7/site-packages/skill_metrics/overlay_taylor_diagram_circles.py", line 51, in overlay_taylor_diagram_circles
    xunit[inds[1:3:2]] = np.zeros(2)
ValueError: shape mismatch: value array of shape (2,) could not be broadcast to indexing result of shape (1,)
```

**Comment by map06** [comment]
I am also having same issue.

**Comment by dverfaillie** [comment]
I also have the same issue, with any sample.
Is it because we are using Python 2.7? In overlay_taylor_diagram_circles.py, I saw that the operator // (integer division) is used. I'm not sure this would work in Python 2.7, would it?

**Comment by geoblog** [comment]
HI,is this question solved?I am using py3.5 and got the same error as above.
xunit[inds[1:3:2]] = np.zeros(2)    
yunit[inds[0:4:2]] = np.zeros(3)
this caused shape mismatch error.

**Comment by PeterRochford** [comment]
I have just pushed new updates of the Skill Metrics package to GitHub. The latest taylor1.py runs for me using both python2 and python3. I hope to publish a new version via pip within the next couple of days.

**Comment by PeterRochford** [comment]
Problem has been resolved with the publishing of SkillMetrics Version 1.1.6 via pip.
