### ISSUE TITLE
Plot taylor_diagram inside subplots

### ISSUE THREAD

**Issue by ashesh-0** [PeterRochford/SkillMetrics#22]
Hello, 
I was looking to plot the taylor diagram inside matplotlib's subplots. Something like:
```
thresholds = [-1, 1, 2, 5, 10, 20, 30]
_,ax = plt.subplots(figsize=(3*len(thresholds), 3), ncols=len(thresholds))

for i, threshold in enumerate(thresholds):
    mask = tar > threshold
    stats = sm.taylor_statistics(pred[mask], tar[mask])
    sdev = np.array([stats['sdev'][0], stats['sdev'][1]])
    crmsd = np.array([stats['crmsd'][0], stats['crmsd'][1],])                     
    ccoef = np.array([stats['ccoef'][0], stats['ccoef'][1]])

    sm.taylor_diagram(sdev,crmsd,ccoef,markerLabel=['Target','Pred'],markerLegend='on', ax=ax[i])
plt.show()
```
I don't see `taylor_diagram` supporting `ax` arguement. Do let me know if there is already some (even hacky) way to do this. 
Thanks !!

**Comment by pierreloicq** [comment]
For people of the future:
It worked for me, you need something like this in your loop: 
ax[rowIndexInYourSubplot, colIndexInYourSubplot] = plt.subplot( numberOfRows, numberOfCols, posOfCurrentSubplot )
Maybe it works also with a "one index" subplot (only 1 row or 1 col), cfr subplot doc

**Comment by xiuyongwu** [comment]
hello, is there any process in using taylor_diagram in the plt.subplots?

**Comment by PeterRochford** [comment]
The capability to plot target and taylor diagrams inside matplotlib's subplots is now available in SkillMetrics 1.2.1 (released 9/5/2022). Refer to the following examples that use this capability: 

[Target Diagram Example 9](http://github.com/PeterRochford/SkillMetrics/wiki/Target-Diagram-Example-9)
[Taylor Diagram Example 14](http://github.com/PeterRochford/SkillMetrics/wiki/Taylor-Diagram-Example-14)

**Comment by collinsowusu** [comment]
"pip install SkillMetrics --upgrade" doesn't install the latest update (1.2.1). It still installs version 1.1.8

I tried specifying the version to install but got this error:
"No matching distribution found for SkillMetrics==1.2.1"

**Comment by PeterRochford** [comment]
Collins,

The latest version of SkillMetrics only supports Python 3. Try the following command instead:

pip3 install SkillMetrics --upgrade

It works fine for me in installing version 1.2.1. I have updated the documentation on the Wiki home <https://github.com/PeterRochford/SkillMetrics/wiki> page accordingly. 

The project description on the PyPI page will not get updated until I post a new release. 

Peter Rochford

**Comment by collinsowusu** [comment]
Hello Peter,

I use Python 3.  I have uninstalled the previous version and even purged pip's cache but it still installs version 1.1.8.

Below is the results of my installation process:
![image](https://user-images.githubusercontent.com/59980223/188958400-490a03a5-c1da-4e95-ad6d-4035ed4aff06.png)

**Comment by PeterRochford** [comment]
Perhaps there is a conflict with anaconda3 which you appear to have installed on your computer. I don't use anaconda, but according to my internet search you need to start anaconda and then install from within that environment. The steps appear to be:

1. Open Anaconda Command prompt as administrator
2. pip install SkillMetrics

I hope this helps.

**Comment by collinsowusu** [comment]
Hello Peter,

Thanks for your help. I installed it within my working environment but it didn't resolve the problem.

I downloaded the SkillMetrics code from the repository and imported it directly, which works for me.

I still don't know why the pip install is not working for me.

**Comment by PeterRochford** [comment]
Thank you for the update. Since you've solved your problem I will now close this issue.

**Comment by ogunjosam** [comment]
> Hello Peter,
> 
> Thanks for your help. I installed it within my working environment but it didn't resolve the problem.
> 
> I downloaded the SkillMetrics code from the repository and imported it directly, which works for me.
> 
> I still don't know why the pip install is not working for me.

Hello @collinsowusu ,

I am currently having the same issue with installing SkillMetrics -1.2.1 using Google Colab.  Can you share the process of downloading and importing the code directly? 

All attempts to install version 1.2.1 failed. 

Thank you.

**Comment by collinsowusu** [comment]
Hello @ogunjosam,

Open the SkillMetrics code repository and download the code as zip. Unzip and copy the skill_metrics folder to the location of your code. 

You can then do:  "import skill_metrics as sm"
Python will first look at the package folder at your code location before it will search in any other location on your computer so it will import the from the folder you downloaded.

Collins

**Comment by ogunjosam** [comment]
> Hello @ogunjosam,
> 
> Open the SkillMetrics code repository and download the code as zip. Unzip and copy the skill_metrics folder to the location of your code.
> 
> You can then do: "import skill_metrics as sm" Python will first look at the package folder at your code location before it will search in any other location on your computer so it will import the from the folder you downloaded.
> 
> Collins

Thank you so much.

**Comment by PeterRochford** [comment]
@collinsowusu: Thank you for posting a solution. I've added it to the FAQ under [Installation Issues](https://github.com/PeterRochford/SkillMetrics/wiki/FAQ#installation-issues) as Q2.
