### ISSUE TITLE
The RMSD value inputed by csv file is different with the RMSD value in the Taylor Diagrme  on the same model

### ISSUE THREAD

**Issue by Jackli9218** [PeterRochford/SkillMetrics#25]
I imported the CSV data containing RMSD into Python Idle, but the graphs generated through the Skill_Metrics Python package show  individual model RMSD values that are different from the RMSD values of the raw CSV data.

**Comment by PeterRochford** [comment]
Without having access to your raw data and the Python plotting script, my guess is that you are making the mistakes cited in the [FAQ Plotting Issues](https://github.com/PeterRochford/SkillMetrics/wiki/FAQ#plotting-issues) Q8 and Q9.  Try reading these items and then checking how you calculate the RMSD values of your raw data.
