### ISSUE TITLE
Cannot change the label

### ISSUE THREAD

**Issue by AmenehTavakol** [PeterRochford/SkillMetrics#3]
This is a great package but my label are not readable. How can I change the font and size of "correlation coefficient" and STD? 
![555](https://user-images.githubusercontent.com/35605408/37008687-ee4e0dee-20a8-11e8-9d5f-e2af6cc92709.gif)

**Comment by PeterRochford** [comment]
Refer to the answer to Question 6 in the [FAQ](https://github.com/PeterRochford/SkillMetrics/wiki/FAQ) of the GitHub Wiki page.
