### ISSUE TITLE
cmap is not use!!!

### ISSUE THREAD

**Issue by ninghaitao** [PeterRochford/SkillMetrics#32]
I am glad that the author can create such an excellent package, but after updating to the latest version, parameters such as cmap and cmap_marker are still unavailable

**Comment by PeterRochford** [comment]
Have you done a "git pull" to make sure your fork of the git repository is up to date? 

If you are still having problems, then please provide an example. The parameters cmap and cmap_marker work for me in my tests. 

Note that I just released a new version of the SkillMetrics package via pip. To upgrade, run in a terminal window the command:
pip3 install SkillMetrics --upgrade

**Comment by PeterRochford** [comment]
I have added another example that illustrates how to create a target diagram with a color bar for a specified color map ([Target Diagram Example 10](https://github.com/PeterRochford/SkillMetrics/wiki/Target-Diagram-Example-10)).  Using the cmap and cmap_marker options are identical for Taylor diagrams. 

This should address your issue.
