### ISSUE TITLE
bold ticks

### ISSUE THREAD

**Issue by san57** [PeterRochford/SkillMetrics#36]
Hi,
Great thanks to make available such great and flexible python scripts!

I would like to increase the font size of labels and ticks on each axis. 

May you kindly help me with it?

With regards
Santanu

**Comment by PeterRochford** [comment]
Santanu,

You can easily change the size of the fonts on the target and Taylor diagrams by referring to [FAQ Plotting Issues](https://github.com/PeterRochford/SkillMetrics/wiki/FAQ#plotting-issues) Q4. 

The tick size is hardcoded and would not be easy to make adjustable. 

Regards,
Peter

**Comment by PeterRochford** [comment]
I assume my response answered the question.

**Comment by PeterRochford** [comment]
I assume my response answered the question.
