### ISSUE TITLE
request 

### ISSUE THREAD

**Issue by itar-kh** [PeterRochford/SkillMetrics#7]
Is there a way to add bias to the Taylor diagram? Like the attached image

![om7a0](https://user-images.githubusercontent.com/43762960/50497469-1a35be00-0a4d-11e9-80dc-9479354932e0.png)

**Comment by PeterRochford** [comment]
I have just pushed new updates of the Skill Metrics package to GitHub with an example script (taylor11.py) that supports such a capability. I hope to publish a new version of the package via pip within the next couple of days.

**Comment by PeterRochford** [comment]
This capability is now available in SkillMetrics Version 1.1.6 that has now been published via pip.
